plugins:
  - serverless-offline
service: test

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221




functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
